############################################################################
#   ____ ____   ___  ____    ____  _____ _____ _____ ___ _   _  ____ ____  #
#  / ___|  _ \ / _ \|  _ \  / ___|| ____|_   _|_   _|_ _| \ | |/ ___/ ___| #
# | |   | |_) | | | | |_) | \___ \|  _|   | |   | |  | ||  \| | |  _\___ \ #
# | |___|  _ <| |_| |  __/   ___) | |___  | |   | |  | || |\  | |_| |___) |#
# \____|_| \_\\___/|_|     |____/|_____| |_|   |_| |___|_| \_|\____|____/  #
#                                                                          #
############################################################################
Crop-Settings:
  Wheat:
    enabled: true
  Potato:
    enabled: true
  Carrot:
    enabled: true
  NetherWart:
    enabled: true
  CocoaBean:
    enabled: true
  Beetroot:
    enabled: true
  Pumpkin:
    enabled: true
  Melon:
    enabled: true
  SugarCane:
    enabled: true
  Bamboo:
    enabled: true
  Pitcher:
    enabled: true